import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  sidebar: [
    {
      type: "category",
      collapsible: false,
      collapsed: false,
      label: "Onboarding",
      items: ["onboarding/overview"],
    },
    {
      type: "category",
      collapsible: false,
      collapsed: false,
      label: "Get Started",
      items: [
        "index",
        {
          type: "category",
          collapsible: true,
          collapsed: false,
          label: "Product",
          items: [
          {
            type: "category",
            collapsible: true,
            collapsed: false,
            label: "Savings",
            items: [
              "product/savings/volume_discounts", 
              "product/savings/savings_plans", 
              "product/savings/reserved_instances",
              "product/savings/tax",
            ]},
          {
            type: "category",
            collapsible: true,
            collapsed: false,
            label: "Guardrails",
            items: [
              "product/guardrails/anomalies", 
              "product/guardrails/rightsizing"
            ]}
            ,
            {
              type: "category",
              collapsible: true,
              collapsed: false,
              label: "Visibility",
              items: [
                "product/visibility/dashboard",
                "product/visibility/budgets", 
              ]}
          ],
        },
        {
          type: "category",
          collapsible: true,
          collapsed: false,
          label: "Security and Access Control",
          items: ["security/iam_roles"]
        },
        {
          type: "category",
          collapsible: true,
          collapsed: false,
          label: "Billing",
          items: ["billing/invoices"]
        },
      ],
    },
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
