import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  sidebar: [
    {
      type: "category",
      collapsible: false,
      collapsed: false,
      label: "Getting Started",
      items: [
        "index",
        {
          type: "category",
          collapsible: true,
          collapsed: true,
          label: "Onboarding",
          items: [
            "onboarding/overview",
            "onboarding/account_creation",
            "onboarding/iam_role_creation",
            "onboarding/payment",
            "onboarding/company_info",
            "onboarding/join_org",
          ],
        },
      ],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Product",
      items: [
        {
          type: "category",
          collapsible: true,
          collapsed: true,
          label: "Settings",
          items: [
            "features/settings/workspace",
            "features/settings/accounts",
            "features/settings/members",
            "features/settings/billing",
          ],
        },
      ],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: true,
      label: "Security and Access Control",
      items: [
        "security/iam_roles_explained",
        "security/aws_permissions",
        "security/organization_changes",
      ],
    },
    {
      type: "category",
      collapsible: false,
      collapsed: false,
      label: "Billing",
      items: ["billing/invoicing"],
    },
    {
      type: "category",
      collapsible: false,
      collapsed: false,
      label: "FAQ",
      items: ["faq/index"],
    },
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
